# Generated by Django 4.1.1 on 2022-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAvanci", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fecha_inicio",
            field=models.DateField(null=True),
        ),
    ]
