# Generated by Django 4.1.1 on 2022-10-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppAvanci", "0002_curso_fecha_inicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="fecha_inicio",
        ),
    ]
