# Generated by Django 4.1.1 on 2022-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppAvanci", "0003_remove_curso_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fecha_inicio",
            field=models.DateField(null=True),
        ),
    ]
